delicious_date_night/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/about' => 'welcome#about'

  get '/landing' => "welcome#landing"

  get 'session/new' => 'session#new'

  post 'session' => 'session#create'

  get 'session/delete' => 'session#destroy'

  get 'events/:id' => 'events#show'

  get '/profile' => "couples#profile"

  resources :couples do

    resources :favorites, only: [:create, :destroy]
    resources :events, except: [:show, :index]
    resources :date_nights, {shallow: true}

  end

    resources :date_nights, except: [:new, :create, :index]

end

delicious_date_night/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	# GET '/'
	# render welcome page
	def index
		# if current_user
		# 	render html: 'logged'
		# else
		# 	render html: 'not logged in'
		# end
	end

	# GET '/about'
	# render FAQ page
	def about
		render(:about)
	end

	# GET '/landing'
	# render landing page
	def landing
		if session[:couple_id]
			@couple = Couple.find(session[:couple_id])
			@couples = Couple.where("id != #{session[:couple_id]}")
			@foods = Food.all
			@events = Event.all
			render(:landing)
		else
			redirect_to '/'
		end
	end

end

delicious_date_night/app/views/welcome/about.html.erb
<div class="container about-list">
  <ul class="nav nav-pills">
    <li role="presentation" class="active"><a href="#" id="about">About</a></li>
    <li role="presentation" ><a href="#" id="faq">FAQ</a></li>
    <li role="presentation"><a href="#" id="testimonials">Testimonials</a></li>
  </ul>

  <div class="about details active">
    <p>Delicious Date Night &#0153; is an innovative new website designed to bring together couples with similar interests and hobbies. With our intuitive interface as a guide, you and your significant other will be on your way to creating fun and meaningful friendships in less time than it takes to order takeout. Our fun events include everything from ice skating to karaoke to bingo nights with the gals.</p> 

    <p>For the first fifty couples to sign up we are giving out vouchers to a Rangers game plus 50% off hot pretzels for everyone!</p>

    <p>Join today and discover for yourself how new friends can add to your relationship, no matter what stage of life you are in.</br></p> 
    <a  class="date-link" href="couples/new"><h3>Go on a Delicious Date!</h3></a>

  </div>

  <div class="faq details">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Who can join Delicious Date Night &#0153;?</h3>
      </div>
      <div class="panel-body">
        Everybody! We welcome couples of all ages, types and genders. The wide range of couples on our site makes for an exciting adventure each time you go on a Delicious Date. We do ask that you sign up for Delicious Date Night&#0153; togther with your partner to ensure an even number of people on your date. Remember, three's a crowd but four's a partay! (disclaimer: minors under 18 years of age must be chaperoned by an adult)
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">How does Delicious Date Night&#0153; work?</h3>
      </div>
      <div class="panel-body">
       It's easy! When you sign up for Delicious Date Night&#0153; you are given access to a list of other user couples, as well as creative and fun ideas for date nights. You can choose any couple from the list and ask them out on a date. To create your itinerary, choose from a wide variety of drinks, activities, and foods to plan the perfect double date.
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">What sorts of activities make up a Delicious Date? </h3>
      </div>
      <div class="panel-body">
        Lots! Our events coordinators are constantly adding new events to our selection. User feedback is taken strong into account and we are always open to hearing your suggestions for new activities, foods or drinks. At Delicious Date Night&#0153; we aim to please every personality and palate.  
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Is there a charge to sign up for the site?</h3>
      </div>
      <div class="panel-body">
        No! Registration is absolutely free and you are never charged a fee for using the site.
      </div>
    </div>
  </div>

  <div class="testimonials details">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"> Jenny and Jim, NYC</h3>
  </div>
  <div class="panel-body testimonials details">
      <p>"My husband and I were so excited when we heard about this new double dating website. We're new in the area and were having a hard time meeting other couples to hang out with. Delicious Date Night solved that problem by opening up a world of social opportunities that we never would have found on our own. We discovered great neighborhood gems from our dating partners and have made new friends for life. Thank you Delicious Date Night!!"</p>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"> Marge and Wilson, New York</h3>
  </div>
  <div class="panel-body testimonials details">
    <p>"As a couple in our eighties, my wife and I had given up on the idea of making new friends. Where would we find new friends at our age? Then our grandson told us about Delicious Date Night. Being computer savvy, my wife signed us up and the next week we met our new friends Sally and Wilma. This website is just wonderful and we'll be telling everyone in our retirement village about it."
    </p>  
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">- Brendan and Lana, Seattle WA</h3>
  </div>
  <div class="panel-body testimonials details">
     <p>"This website ROCKS!! My bf and I were looking for other cool couples in the area to play paintball with. We found Mike and Mindy on Delicious Date Night and did paintball with them 3 times. It was awesome!! And so are Mindy and Mike!!! And so is delicious date night!!!!"
    </p>
  </div>
</div>
</div>

delicious_date_night/app/views/welcome/faq.html.erb
<div class="container about-list">
  <ul class="nav nav-pills">
    <li role="presentation" class="active"><a href="#" id="about">About</a></li>
    <li role="presentation" ><a href="#" id="faq">FAQ</a></li>
    <li role="presentation"><a href="#" id="testimonials">Testimonials</a></li>
  </ul>

  <div class="about details active">
    <p>About stuff here</p>
  </div>

  <div class="faq details">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Panel title</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Panel title</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Panel title</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Panel title</h3>
      </div>
      <div class="panel-body">
        Panel content
      </div>
    </div>
  </div>

  <div class="testimonials details">
    <p>Testimonials stuff here</p>
  </div>

</div>

delicious_date_night/app/views/welcome/index.html.erb
	<div class = "wrapper">
<section class="jumbotron">
	<div class="container">
		<h1 class="title">Delicious Date Night</h1>
		<p><a class="btn btn-primary btn-md" href="<%= new_couple_path %>" role="button">Signup</a></p>
	</div>
</section>
	</div>

<section class="container">
	<div id = "statement">
	<h3>Date Night Will Never Be The Same!</h3>
	</div>
</section>

delicious_date_night/app/views/welcome/landing.html.erb
<div class="container">
<h1>Make a Delicious Date!</h1>
</div>

<div class="container">
	<section class="couples">
		<h2>Find Some Friends!</h2>
		<% @couples.each do |couple| %>
			<div class="col-sm-4">
				<div class="panel panel-success">
					<div class="panel-heading">
						<h3 class="panel-title"><strong> <%= couple.a_fname %> and <%= couple.b_fname %> </strong></h3>
					</div>
					<div class="panel-body">
						<a href="/couples/<%= couple.id %>"><img src= "<%= couple.avatar %>" alt="..." class="couple-image"></a>
						<br><br>
						<form action="/couples/<%= @couple.id %>/date_nights/new" method="GET">
			  			<input type="hidden" name= "receiver_id" value="<%= couple.id %>">
			  			<button class="btn btn-success">Make a Date!</button>
			  		</form>
					</div>
				</div>
			</div>
		<% end %>
	</section>
</div>

	<br>
<div class="container">
	<section>
		<h2>Choose a Sweet Themed Date</h2>
		<h3>...or <a href="/couples/<%= @couple.id %>/events/new">create your own</a>!</h3>
		<% @events.each do |event| %>
			<div class="col-sm-4">
				<div class="panel panel-warning">
					<div class="panel-heading">
						<h3 class="panel-title"><strong><%= event.event_theme %></strong></h3>
					</div>
					<div class="panel-body">
						<a href="/events/<%= event.id %>"><img src= "<%= event.activity.picture_url %>" alt="..." class="couple-image"></a>
						<br><br>
						 <form action="/couples/<%= @couple.id %>/date_nights/new" method="GET">
			  			<input type="hidden" name= "event_id" value="<%= event.id %>">
			  			<button class="btn btn-warning">Make a Date!</button>
			  		</form>
					</div>
				</div>
			</div>
		<% end %>
	</section>
</div>