delicious_date_night/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/about' => 'welcome#about'

  get '/landing' => "welcome#landing"

  get 'session/new' => 'session#new'

  post 'session' => 'session#create'

  get 'session/delete' => 'session#destroy'

  get 'events/:id' => 'events#show'

  get '/profile' => "couples#profile"

  resources :couples do

    resources :favorites, only: [:create, :destroy]
    resources :events, except: [:show, :index]
    resources :date_nights, {shallow: true}

  end

    resources :date_nights, except: [:new, :create, :index]

end

delicious_date_night/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeliciousDateNight</title>
  <link href='http://fonts.googleapis.com/css?family=Didact+Gothic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>

<nav class="navbar navbar-default">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Delicious Date Night</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/about">About</a></li>
        <% if current_user %>
          <li><a href="<%= landing_path %>">Home</a></li>
          <li><a href="<%= profile_path %>">Our Profile</a></li>
          <li><a href="<%= session_delete_path %>">Logout</a></li>
        <% else %>
          <li><a href="<%= session_new_path %>">Login</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<body>

<%= yield %>

</body>
</html>